name: Swiftlint

# Controls when the workflow will run
on:
  pull_request:

jobs:
  lint:
    runs-on: macos
    steps:
      - uses: actions/checkout@v3

      - name: install swiftlint
        run: brew install swiftlint
        
      - name: run swiftlint
        run: swiftlint lint
